definitions:
    Campaign:
        description: Campaign represents a promotional campaign
        properties:
            created_at:
                format: date-time
                type: string
                x-go-name: CreatedAt
            creator:
                $ref: '#/definitions/User'
            creator_id:
                description: Foreign key relationship with User model (if applicable)
                format: uint64
                type: integer
                x-go-name: CreatorID
            discount_percentage:
                format: double
                type: number
                x-go-name: Discount
            end_date:
                format: date-time
                type: string
                x-go-name: EndDate
            id:
                format: uint64
                type: integer
                x-go-name: ID
            max_users:
                format: int64
                type: integer
                x-go-name: MaxUsers
            name:
                type: string
                x-go-name: Name
            start_date:
                format: date-time
                type: string
                x-go-name: StartDate
            status:
                type: string
                x-go-name: Status
            updated_at:
                format: date-time
                type: string
                x-go-name: UpdatedAt
        type: object
        x-go-package: github.com/luongquochai/promotional-campaign-system/models
    Purchase:
        description: Purchase represents a user's purchase details for a campaign
        properties:
            created_at:
                format: date-time
                type: string
                x-go-name: CreatedAt
            discount_applied:
                format: double
                type: number
                x-go-name: DiscountApplied
            final_price:
                format: double
                type: number
                x-go-name: FinalPrice
            id:
                format: uint64
                type: integer
                x-go-name: ID
            status:
                type: string
                x-go-name: Status
            subscription_id:
                format: uint64
                type: integer
                x-go-name: SubscriptionID
            transaction_id:
                type: string
                x-go-name: TransactionID
            updated_at:
                format: date-time
                type: string
                x-go-name: UpdatedAt
            user_id:
                format: uint64
                type: integer
                x-go-name: UserID
        type: object
        x-go-package: github.com/luongquochai/promotional-campaign-system/models
    User:
        description: User represents the user details in the system
        properties:
            created_at:
                format: date-time
                type: string
                x-go-name: CreatedAt
            email:
                type: string
                x-go-name: Email
            id:
                format: uint64
                type: integer
                x-go-name: ID
            password:
                type: string
                x-go-name: Password
            role:
                type: string
                x-go-name: Role
            updated_at:
                format: date-time
                type: string
                x-go-name: UpdatedAt
            username:
                type: string
                x-go-name: Username
        type: object
        x-go-package: github.com/luongquochai/promotional-campaign-system/models
    Voucher:
        description: Voucher represents a discount voucher for a user within a campaign
        properties:
            campaign_id:
                format: uint64
                type: integer
                x-go-name: CampaignID
            code:
                type: string
                x-go-name: Code
            created_at:
                format: date-time
                type: string
                x-go-name: CreatedAt
            discount:
                format: double
                type: number
                x-go-name: Discount
            id:
                format: uint64
                type: integer
                x-go-name: ID
            updated_at:
                format: date-time
                type: string
                x-go-name: UpdatedAt
            used_at:
                format: date-time
                type: string
                x-go-name: UsedAt
            user_id:
                format: uint64
                type: integer
                x-go-name: UserID
            valid_from:
                format: date-time
                type: string
                x-go-name: ValidFrom
            valid_to:
                format: date-time
                type: string
                x-go-name: ValidTo
        type: object
        x-go-package: github.com/luongquochai/promotional-campaign-system/models
    VoucherCampaign:
        description: VoucherCampaign is a wrapper that contains the Voucher and Campaign details
        properties:
            campaign:
                $ref: '#/definitions/Campaign'
            voucher:
                $ref: '#/definitions/Voucher'
        type: object
        x-go-package: github.com/luongquochai/promotional-campaign-system/models
    UserLogin:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
    responses:
      successResponse:
        description: Request was successful
        schema:
          type: object
          properties:
            message:
              type: string

      badRequest:
        description: Invalid request
        schema:
          type: object
          properties:
            error:
              type: string

      internalServerError:
        description: Internal server error
        schema:
          type: object
          properties:
            error:
              type: string
paths: {}
swagger: "2.0"
