dsn: "root:Chipgau164@@tcp(localhost:3306)/promotional_campaign?charset=utf8mb4&parseTime=True&loc=Local"
redis_addr: "localhost:6379"
redis_db: 0
port: ":8080"
db:
  user: root
  password: Chipgau164
  host: localhost:3306
  name: promotional_campaign
